#!/usr/bin/python3

import os
import argparse


def main():
    parser = argparse.ArgumentParser(description='Start CDN')
    parser.add_argument('-p', type=int, required=True, metavar='port')
    parser.add_argument('-o', type=str, required=True, metavar='origin')
    parser.add_argument('-n', type=str, required=True, metavar='name')
    parser.add_argument('-u', type=str, required=True, metavar='username')
    parser.add_argument('-i', type=str, required=True, metavar='keyfile')

    args = parser.parse_args()

    # build_server = "cs5700cdnproject.ccs.neu.edu"
    # build_server = "p5-http-a.5700.network"

    dns_node = "p5-dns.5700.network"
    # replica_servers = ["p5-http-b.5700.network"]
    replica_servers = ["p5-http-a.5700.network", "p5-http-b.5700.network", "p5-http-c.5700.network",
                       "p5-http-d.5700.network", "p5-http-e.5700.network", "p5-http-f.5700.network",
                       "p5-http-g.5700.network"]

    ssh_command = 'ssh -i {} {}@{} "rm -rf ~/li_huang; mkdir li_huang"'.format(args.i, args.u, dns_node)
    os.system(ssh_command)

    copy_command = "scp -i {} dnsserver {}@{}:li_huang/dnsserver".format(args.i, args.u, dns_node)
    os.system(copy_command)
    #
    # copy_command = "scp -i {} mapping.py {}@{}:li_huang/mapping.py".format(args.i, args.u, dns_node)
    # os.system(copy_command)

    for replica in replica_servers:
        ssh_command = 'ssh -i {} {}@{} "rm -rf ~/li_huang; mkdir li_huang"'.format(args.i, args.u, replica)
        os.system(ssh_command)

        copy_command = "scp -i {} httpserver {}@{}:li_huang/httpserver".format(args.i, args.u, replica)
        os.system(copy_command)

        copy_command = "scp -i {} pageviews.csv {}@{}:li_huang/pageviews.csv".format(args.i, args.u, replica)
        os.system(copy_command)


main()
